name: CHALLENGE

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
    types: [opened]
    merged: true


  workflow_dispatch:
    
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{vars.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: msanchez@devcenter.es
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
